FROM php:7.1.2-apache
MAINTAINER Javier Cifuentes <jcifuentes91@hotmail.com>

ENV APACHE_DOCUMENT_ROOT /var/www/BridgeLoanNetwork
ADD docker /var/www/BridgeLoanNetwork
COPY docker/conf/php-development.ini /usr/local/etc/php/
RUN a2enmod rewrite
RUN a2enmod headers

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

#Install dependencies
RUN apt-get update
RUN apt-get install -my zip unzip curl wget gnupg libpng-dev libssl-dev libcurl4-openssl-dev nano gcc make libc-dev pkg-config
#Install gd with jpeg support
RUN apt-get install -y libmcrypt-dev
RUN apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

# Install Packages
RUN docker-php-ext-install mysqli pdo pdo_mysql curl zip
# Install composer
RUN curl -sS https://getcomposer.org/installer | php && \
 mv composer.phar /usr/local/bin/composer

# Install Node.js
RUN apt-get install -y iputils-ping net-tools vim-tiny less

#RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
#  apt-get install -y nodejs

# Install npm
#RUN apt-get install -y npm

WORKDIR /var/www/BridgeLoanNetwork

RUN pecl install redis-4.0.1 \
    && pecl install --nodeps mcrypt-snapshot \
    && pecl install --nodeps mailparse \
    && pecl install xdebug-2.6.0 \
    && docker-php-ext-enable redis xdebug

COPY docker/conf/php-development.ini /usr/local/etc/php/php.ini