version: '3'
services:
    bln_db:
      image: mysql:5.7
      ports:
        - 3306:3306
      restart: always
      volumes:
        - ./conf/db:/docker-entrypoint-initdb.d
        - ./conf/mysql:/etc/mysql/conf.d
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: master_admin
        MYSQL_PASSWORD: master_admin
        DB_HOSTNAME: bln_db
        DB_USERNAME: master_admin
        DB_PASSWORD: master_admin
        DB_DATABASE: staging_loans

    bln_redis:
      image: redis
      restart: always
      ports:
        - "6379:6379"
        
    bln_web:
      depends_on:
        - bln_db
      tty: true
      build:
        context: ../
        dockerfile: Dockerfile
      restart: always
      ports:
         - "80:80"
         - "443:443"
      volumes:
        - ../repos/:/var/www/repos:rw
        - ./conf:/conf:rw
      links:
        - "bln_db"
        - "bln_redis"

    bln_wordpress:
      depends_on:
        - bln_db
        - bln_web
      image: wordpress:4.9
      environment:
      - WORDPRESS_DB_HOST=bln_db:3306
      - WORDPRESS_DB_USER=master_admin
      - WORDPRESS_DB_PASSWORD=master_admin
      - WORDPRESS_DB_NAME=wordpress
      restart: always    
      ports: 
        - "8080:80"
      extra_hosts:
        - "api.localbln:172.18.0.4"
      volumes:
        - ../repos/WordPressPlugin:/var/www/html/wp-content/plugins/bridgeloannetwork:rw
      links:
        - "bln_db"
        - "bln_web"