version: '3'
services:
    bln_db:
      image: mysql
      ports:
        - 3306:3306
      restart: always
      volumes:
        - ./conf/db:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: root

    bln_web:
      depends_on:
        - bln_db
      tty: true
      build:
        context: ../
        dockerfile: DockerFile 
      ports:
        - "80:80"
      volumes:
        - ../:/var/www/BridgeLoanNetwork
        - ./conf:/conf
      links:
        - "bln_db"