version: '3'
services:
    bln_db:
      image: mysql:5.7
      ports:
        - 3306:3306
      restart: always
      volumes:
        - ./conf/db:/docker-entrypoint-initdb.d
        - ./conf/mysql:/etc/mysql/conf.d
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: master_admin
        MYSQL_PASSWORD: master_admin
        DB_HOSTNAME: bln_db
        DB_USERNAME: master_admin
        DB_PASSWORD: master_admin
        DB_DATABASE: staging_loans

    bln_redis:
      image: redis
      restart: always
      ports:
        - "6379:6379"

##    bln_traefik:
##      image: traefik:v2.2
##      command:
##        - --entrypoints.web-secure.address=:443
##        - --api.insecure=true
##        - --providers.docker
##        - --providers.file.directory=/configuration/
##        - --providers.file.watch=true
##      ports:
##        - "8080:8080"
##        - "80:80"
##        - "443:443"
##      volumes:
##        - "./conf:/configuration:ro"
##        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    

##    bln_cake3:
##      depends_on: 
##        - bln_db
##      tty: true
##      build:
##        context: ../
##        dockerfile: Dockerfile.cake3
##      ports:
##        - "8080:80"
##        - "4443:443"
##       restart: always
##        labels:
##          - "traefik.enable=true"
##          - "traefik.tcp.routers.blnlocal.rule=HostSNI(`*.devel-blnsoftware.com`)"
##          - "traefik.tcp.routers.blnlocal.tls=true"
##          - "traefik.tcp.routers.blnlocal.tls.passthrough=true"
##          - "traefik.tcp.services.blnlocal.loadbalancer.server.port=443"
##      volumes:
##        - ../repos/BridgeLoanNetworkUpgrade:/var/www/BridgeLoanNetwork
##        - ./conf:/conf
##      links:
##        - "bln_db"
##        - "bln_redis"   
          
    bln_web:
      depends_on:
##        - bln_traefik
        - bln_db
      tty: true
##      labels: 
##        - "traefik.enable=true"
##        - "traefik.tcp.routers.blnlocal.rule=HostSNI(`*bln.local`)"
##        - "traefik.tcp.routers.blnlocal.tls=true"
##        - "traefik.tcp.routers.blnlocal.tls.passthrough=true"
##        - "traefik.tcp.services.blnlocal.loadbalancer.server.port=443"
      build:
        context: ../
        dockerfile: Dockerfile
      restart: always
      ports:
         - "80:80"
         - "443:443"
      volumes:
        - ../repos/:/var/www/repos
        - ./conf:/conf
      links:
        - "bln_db"
        - "bln_redis"